#### Random Forest
Random Forest is a supervised learning algorithms. <br>
Used for classification and regression. <br>

It is a meta estimator that fits a number of decision tree classfiers on various sub-samples of the dataset 
A forest is comprised of trees. <br>

The sub-sample size is controlled with the max_samples parameter if bootstrap=True(default), otherwise the whole dataset is used to build each tree.<br>

The more trees it has, the more robust a forest is. <br>

#### Method of random forest
It creates decision trees on randomly selected data samples, <br>
gets prediction from each tree and selects the bebst solution by<br>
by means of VOTING.

#### Random Forest Parameters

n_estimators: Number of Trees in this Forest, deaful = 100 

criterion: {'gini', 'entropy', 'log_loss'}, defaul = 'gini'

max_depth: int, default = None

min_samples_split: int or float, default = 2 

min_samples_leaf: int or float, default = 1

max_leaf_nodes: int, defaul = None

min_impurity_decrase: float, default = 0.0


##### They are same as decision trees but there are some new ones:

bootstrap: bool, defaul = True
If False, the whole dataset is used to build each tree

max_samples: int or float, defaul = None
If bootstrap = True, the number of samples to draw from X to train each base estimator.

In [4]:
# Load Iris dataset
from sklearn.datasets import load_iris
iris = load_iris()

X, Y = iris.data, iris.target

In [6]:
from sklearn.ensemble import RandomForestClassifier

RF = RandomForestClassifier(n_estimators = 100)

RF = RF.fit(X, Y)

#### Random Forest Attributes


In [17]:
RF.estimators_
# List of decision trees in this forest

[DecisionTreeClassifier(max_features='auto', random_state=284805418),
 DecisionTreeClassifier(max_features='auto', random_state=5282453),
 DecisionTreeClassifier(max_features='auto', random_state=130874757),
 DecisionTreeClassifier(max_features='auto', random_state=1893378411),
 DecisionTreeClassifier(max_features='auto', random_state=1405306924),
 DecisionTreeClassifier(max_features='auto', random_state=482256926),
 DecisionTreeClassifier(max_features='auto', random_state=59228800),
 DecisionTreeClassifier(max_features='auto', random_state=1626378881),
 DecisionTreeClassifier(max_features='auto', random_state=1199461806),
 DecisionTreeClassifier(max_features='auto', random_state=174572943),
 DecisionTreeClassifier(max_features='auto', random_state=1360419627),
 DecisionTreeClassifier(max_features='auto', random_state=1239053597),
 DecisionTreeClassifier(max_features='auto', random_state=1899125175),
 DecisionTreeClassifier(max_features='auto', random_state=1558585770),
 DecisionTreeCl

In [18]:
RF.classes_
# List of Classes

array([0, 1, 2])

In [20]:
RF.n_classes_
# Number of Classes

3

In [21]:
RF.n_features_in_
# Number of features used

4

In [27]:
RF.feature_importances_
# the impurity-based feature importances

array([0.11628803, 0.02528572, 0.39216465, 0.46626161])

In [30]:
RF.predict([[6,5,5,1.56]])
# To predict a new datapoint

array([1])

In [31]:
RF.decision_path([[6,5,5,1.56]])

(<1x1696 sparse matrix of type '<class 'numpy.int64'>'
 	with 545 stored elements in Compressed Sparse Row format>,
 array([   0,    7,   24,   43,   60,   81,   92,  113,  132,  149,  174,
         195,  222,  237,  246,  267,  286,  305,  324,  343,  364,  381,
         390,  405,  420,  433,  448,  465,  480,  495,  514,  525,  540,
         555,  574,  595,  612,  623,  650,  665,  680,  695,  706,  721,
         740,  755,  774,  787,  804,  819,  834,  849,  862,  875,  890,
         905,  926,  949,  966,  983,  992, 1011, 1030, 1049, 1064, 1085,
        1098, 1117, 1132, 1145, 1162, 1183, 1202, 1225, 1240, 1261, 1278,
        1301, 1320, 1339, 1352, 1365, 1384, 1395, 1416, 1435, 1452, 1471,
        1492, 1509, 1536, 1551, 1566, 1577, 1602, 1615, 1632, 1649, 1660,
        1675, 1696]))

In [33]:
# RF.fit(X, Y)
# to train the classifier

In [35]:
from sklearn import metrics
from sklearn.model_selection import train_test_split

RF = RandomForestClassifier()
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25, random_state=1)
RF = RF.fit(X_train, Y_train)
Y_pred = RF.predict(X_test)

In [36]:
metrics.accuracy_score(Y_test, Y_pred)

0.9736842105263158